# docker-compose.yml

version: '3.8'

services:

  mysql:
    image: mysql
    restart: always
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: aellink
      MYSQL_DATABASE: aellink

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    depends_on:
      - mysql
    ports:
      - 80:8000
    volumes:
      - ./:/code
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'

volumes:
  redis:
  mysql: